Update hooks

diff --git a/.pbuilder-hooks/I10apt-ftparchive b/.pbuilder-hooks/I10apt-ftparchive
--- a/.pbuilder-hooks/I10apt-ftparchive
+++ b/.pbuilder-hooks/I10apt-ftparchive
@@ -32,10 +32,10 @@ echo Calling "$0"
 echo "Running apt-ftparchive for $DIST-$ARCH"
 
 # Run the name remap code
-. "$PBUILDER_HOOKS/common-name-remapping"
+source "$PBUILDER_HOOKS/common-name-remapping"
 
 NAME="$DIST-$ARCH"
-BUILDRESULT="/var/cache/pbuilder/$NAME/result"
+#BUILDRESULT="/var/cache/pbuilder/$NAME/result"
 
 # Sanity check!
 if [ ! -d "$BUILDRESULT" ]; then
@@ -50,16 +50,19 @@ PBUILDER_REPO=$(cat $BUILDRESULT/.local_repository_location)
 PBUILDER_GPG="$PBUILDER_REPO/gpg"
 
 # move built packages to localrepo
-if [[ ! -z $(ls "$BUILDRESULT") ]]; then
-    if ! mv -t "$PBUILDER_REPO/$NAME" "$BUILDRESULT/*" ; then
+if [ -n "$(ls "$BUILDRESULT")" ]; then
+    if ! mv -t "$PBUILDER_REPO/$NAME" "$BUILDRESULT"/* ; then
         fatal "Failed to move build packages to local repository"
     fi
 fi
 
 # chown the files back to the owning user
-if ! chown "$(stat -c '%u:%g' "$PBUILDER_REPO/$NAME")" "$PBUILDER_REPO/$NAME/*"; then
-    fatal "Failed to change the ownership of built packages back to user"
-fi
+owning_user="$(stat -c '%u:%g' "$PBUILDER_REPO/$NAME")"
+while read -r output; do
+    if ! chown "$owning_user" "$output"; then
+        fatal "Failed to change the ownership of built packages back to user: $output"
+    fi
+done < <(find "$PBUILDER_REPO/$NAME" -mindepth 1 -print)
 
 echo "Local Repository Location is: $PBUILDER_REPO/$NAME"
 
diff --git a/pbuilder-repo/manual-prime b/pbuilder-repo/manual-prime
--- a/pbuilder-repo/manual-prime
+++ b/pbuilder-repo/manual-prime
@@ -6,7 +6,7 @@
 
 if [[ $EUID != 0 ]]; then
     echo "Must run as root."
-    sudo $0 $@
+    sudo "$0" "$@"
     exit $?
 fi
 
@@ -17,13 +17,31 @@ if [ -z $1 ]; then
 	echo "No build result proposed. Attempting auto-select of current environment."
 fi
 
-: ${DIST:=$(lsb_release --short --codename)}
-: ${ARCH:=$(dpkg --print-architecture)}
+if [ -z "$pbuilder_user" ]; then
+	pbuilder_user=$SUDO_USER
+	export pbuilder_user
+fi
+echo "PBuilder User: $pbuilder_user"
+
+if [ -z "$pbuilder_user" ]; then
+    fatal "Failed to find a pbuilder username"
+fi
+
+declare -x HOME
+if ! HOME=$( getent passwd "$pbuilder_user" | cut -d: -f6 ); then
+    fatal "Could not find pbuilder_user home directory"
+fi
+
+# Get the distribution names
+: "${DIST:=$(lsb_release --short --codename)}"
+: "${ARCH:=$(dpkg --print-architecture)}"
+
+export PBUILDER_REPO="$HOME/pbuilder/repo"
+export PBUILDER_HOOKS="$HOME/pbuilder/hooks"
+export PBUILDER_CACHE="$HOME/.cache/pbuilder"
+export PBUILDER_GPG="$HOME/pbuilder/repo/gpg"
 
 NAME="$DIST-$ARCH"
+export BUILDRESULT="$PBUILDER_CACHE/$NAME/result"
 
-export PBUILDERHOOKS=~/.pbuilder-hooks
-
-echo "Running D10apt-ftparchive"
-
-DIST=$DIST ARCH=$ARCH ~/.pbuilder-hooks/D10apt-ftparchive
+DIST=$DIST ARCH=$ARCH "$PBUILDER_HOOKS/I10apt-ftparchive"
